runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:server

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.9

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /
  script: main.py
  secure: always
  redirect_http_response_code: 301