runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:server

runtime_config:
  python_version: 3

automatic_scaling:
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.75

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301